### ISSUE TITLE
Unexpected output in test case (try 2)

### ISSUE THREAD

**Issue by droe-nmdp** [Kingsford-Group/bloomtree#10]
Attached is a simple test via script. It creates a tree and then runs two queries. I only expect one to hit, but they both return the same answer. Can you tell me what I'm doing incorrectly?
[test3.txt](https://github.com/Kingsford-Group/bloomtree/files/417237/test3.txt)

**Comment by Bradsol** [comment]
The answer here is actually quite simple but took me a bit to figure out - the fake fasta you are building is not formatted correctly. What you want is:

>seq
ATATAT....

What you wrote was

>seq ATATAT....

If you change the second line to 'echo -e ">seq \n ATATATATATATATATATAT" > insequence2.txt', your test set works for me.

**Comment by droe-nmdp** [comment]
Thank you! Sorry for the inconvenience.

On 8/24/16, 9:25 AM, "Bradsol" <notifications@github.com<mailto:notifications@github.com>> wrote:

The answer here is actually quite simple but took me a bit to figure out - the fake fasta you are building is not formatted correctly. What you want is:

seq
ATATAT....

What you wrote was

seq ATATAT....

If you change the second line to 'echo -e ">seq \n ATATATATATATATATATAT" > insequence2.txt', your test set works for me.
