### ISSUE TITLE
stdin for count?

### ISSUE THREAD

**Issue by droe-nmdp** [Kingsford-Group/bloomtree#12]
Is there a way to use stdin for 'bt count' instead of an uncompressed file?

**Comment by Bradsol** [comment]
You can pass a filename as an argument or you can pipe in a file (assuming the format of what you are streaming is correct). For example:

./bt count myhash.hh 2e9 <(gunzip myCompressedFasta.fasta.gz) myBF.bf.bv

would produce a bloom filter using the output of gunzip as a file input. Was this what you were asking?

**Comment by droe-nmdp** [comment]
Yes, thank you.
