### ISSUE TITLE
How to run on provided data

### ISSUE THREAD

**Issue by iprada** [Kingsford-Group/bloomtree#14]
Hi!

I am trying to run the bloom tree program on the data provided by you. I have downloaded the data from http://download.srv.cs.cmu.edu/~carlk/sbt/compressedSBT.tar.gz and decompress it. When I decompress it there are 5306 files in the compressedSBT folder.

Looking at the command to query the bloomtree it seems like it should be only one file given as an argument to the command.

`bt query -t 0.8 mySBT.bloomtree myQueryFile.txt myOutFile.txt`

How should I proceed to run the bloomtree script in the dataset provided by you?

**Comment by Bradsol** [comment]
That is correct. The 'bloomtree' file should contain the absolute path to each file in the compressed tar ball and defines the tree architecture of the pre-built SBT. Accordingly you may have to manually adjust these paths in the file to be appropriate to your architecture. But once you have made those changes you can query the SBT by providing a line separated list of sequencing queries in 'myQueryFile.txt'. The output [which will be written to 'myOutFile.txt'] will be a list of all experiments in the dataset which are likely to contain your query. (Multiple queries can be batched together and the results will indicate the total number of hits for each query followed by a line separated list of the specific files).
