### ISSUE TITLE
Build instructions requested.

### ISSUE THREAD

**Issue by ctb** [Kingsford-Group/bloomtree#2]
Is anything other than SDSL needed?

**Comment by ctb** [comment]
And, more generally, what are the various requirements, if known?

**Comment by ctb** [comment]
Jellyfish too, apparently :)

**Comment by ctb** [comment]
Build failure: jellyfish/mer_dna_bloom_counter.hpp not found.  I've got Jellyfish 1.1.11; is there a newer version? Ahh, I see, 2.0...

**Comment by Bradsol** [comment]
The current SBT implementation should run provided you have gcc (Version 4.91 or later), Jellyfish (Version 2.2.0 or later), and SDSL. Did updating Jellyfish resolve the issue?

**Comment by ctb** [comment]
Yep, I got it all working. But it would be nice if so much guessing weren't involved...

**Comment by Bradsol** [comment]
The exact instructions I listed are actually already available on the SBT website ( http://www.cs.cmu.edu/~ckingsf/software/bloomtree/ ) but it is a very good point and I will include similar instructions on the Github web page itself. Thank you for the advice.

**Comment by ctb** [comment]
On Sun, May 31, 2015 at 11:54:59AM -0700, Bradsol wrote:

> The exact instructions I listed are actually already available on the SBT website ( http://www.cs.cmu.edu/~ckingsf/software/bloomtree/ ) but it is a very good point and I will include similar instructions on the Github web page itself. Thank you for the advice.

Ahh, now I found it - yes, sorry, I saw "binary" and ignored everything
below that :)
