### ISSUE TITLE
SDSL vs SDSL-lite 

### ISSUE THREAD

**Issue by rchikhi** [Kingsford-Group/bloomtree#7]
The dependency is SDSL-lite: https://github.com/simongog/sdsl-lite
and not SDSL: https://github.com/simongog/sdsl

**Comment by Bradsol** [comment]
Strictly speaking either installation should be sufficient as the functions used in SBT (bit_vector and rrr_vector) actually exist in sdsl as well as sdsl-lite. However it is a good catch that sdsl is no longer being maintained and I have adjusted the installation instructions to point to the more up-to-date repository. Thanks!

**Comment by rchikhi** [comment]
in the latest version of SDSL (not lite), the API is slightly different (some functions are in sdsl::utils:: namespace instead of sdsl::) and even when making those changes, SBT compiled but crashed when loading a bloom filter. With sdsl-lite, all went fine.
